export const LOREM_IPSUM = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed accumsan tortor.',
  'Praesent eleifend diam eget ipsum condimentum dapibus.',
  'Cras dignissim elit eu eros efficitur aliquam.',
  'Suspendisse semper malesuada quam, sit amet mollis metus accumsan sed.',
  'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
  'Praesent ultricies sollicitudin nunc eget mollis.',
  'Aenean vestibulum ex id lectus hendrerit gravida.',
  'Nam vulputate felis ipsum, at dictum leo dapibus nec.',
  'Phasellus efficitur scelerisque dui, ut viverra odio sodales in.',
  'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
  'Totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
  'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.',
  'Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
  'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.',
  'Sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',
  'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',
  'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
  'Vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
];
